"""add file_data and file_format to resumes

Revision ID: 5ab50c212a66
Revises: 46f1453741ac
Create Date: 2026-06-17 08:59:02.703121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5ab50c212a66'
down_revision: Union[str, None] = '46f1453741ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('file_format', sa.String(length=8), nullable=True))
    op.add_column('resumes', sa.Column('file_data', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'file_data')
    op.drop_column('resumes', 'file_format')
    # ### end Alembic commands ###
